const {
  trim,
  flag,
  split,
  removeIfEmpty
} = require('./formatters');

const subFormats = {
  // for the ubiquitous 53-character geographical identifiers
  GEO_IDENTIFIER_53: [
    ['lowHouseNumber', 16],
    ['highHouseNumber', 16],
    ['boroughCode', 1],
    ['streetCode', 5],
    ['localGroupCode', 2],
    ['bin', 7],
    ['sideOfStreet', 1],
    ['entryType', 1],
    ['binStatus', 1],
    ['_filler', 3]
  ],
  GEO_IDENTIFIER_116: [
    ['lowHouseNumber', 16],
    ['highHouseNumber', 16],
    ['boroughCode', 1],
    ['streetCode', 5],
    ['localGroupCode', 2],
    ['bin', 7],
    ['sideOfStreet', 1],
    ['entryType', 1],
    ['binStatus', 1],
    ['streetName', 32],
    ['_filler', 34]
  ]
};

// formats are keyed by work area and function code
// work area 1 is fixed, so nearly all additions will be to WA2
// there's a lot of duplication here
const formats = {
  WA1_IN: [
    ['functionCode', 2],
    ['houseNumberDisplayFormat', 16],
    ['houseNumberSortFormat', 11],
    ['lowHouseNumberDisplayFormat', 16],
    ['lowHouseNumberSortFormat', 11],
    ['boroughCode1', 1],
    ['streetCode1', 10],
    ['streetName1', 32],
    ['boroughCode2', 1],
    ['streetCode2', 10],
    ['streetName2', 32],
    ['boroughCode3', 1],
    ['streetCode3', 10],
    ['streetName3', 32],
    ['bbl', 10],
    ['_filler', 1],
    ['bin', 7],
    ['compassDirection1', 1],
    ['compassDirection2', 1],
    ['nodeNumber', 7],
    ['workAreaFormat', 1],
    ['zipCode', 5],
    ['unit', 14],
    ['_filler', 82],
    // Flags
    ['longWorkArea2', 1],
    ['houseNumberJustification', 1],
    ['houseNumberNormalizationLength', 2],
    ['houseNumberNormalizationOverride', 1],
    ['streetNameNormalizationLengthLimit', 2],
    ['streetNameNormalizationFormat', 1],
    ['crossStreetNames', 1],
    ['roadbedRequestSwitch', 1],
    ['_filler', 1],
    ['auxiliarySegmentSwitch', 1],
    ['browse', 1],
    ['realStreetsOnly', 1],
    ['TPAD', 1],
    ['mode', 1],
    ['WTO', 1],
  ],

  WA1_OUT: [ // pg 580
    ['firstBoroughName', 9],
    ['houseNumberDisplayFormat', 16],
    ['houseNumberSortFormat', 11],
    ['b10scFirstBorough', 11],
    ['firstStreetNameNormalized', 32],
    ['b10scSecondBorough', 11, removeIfEmpty],
    ['secondStreetNameNormalized', 32, removeIfEmpty],
    ['b10scThirdBorough', 11, removeIfEmpty],
    ['thirdStreetNameNormalized', 32, removeIfEmpty],
    ['bbl', 10, removeIfEmpty],
    ['_fillerTaxLotVersionNumber', 1],
    ['lowHouseNumberDisplayFormat', 16, removeIfEmpty],
    ['lowHouseNumberSortFormat', 11, removeIfEmpty],
    ['bin', 7, removeIfEmpty],
    ['streetAttributeIndicators', 3],
    ['reasonCode2', 1, removeIfEmpty],
    ['reasonCodeQualifier2', 1, removeIfEmpty],
    ['warningCode2', 2, removeIfEmpty],
    ['geosupportReturnCode2', 2, removeIfEmpty],
    ['message2', 80, removeIfEmpty],
    ['nodeNumber', 7],
    ['unitSortFormat', 14],
    ['unitDisplayFormat', 14],
    ['_filler', 11],
    ['napIdentificationNumber', 6],
    ['streetAttributeIndicator', 1],
    ['reasonCode', 1],
    ['reasonCodeQualifier', 1],
    ['warningCode', 2],
    ['geosupportReturnCode', 2],
    ['message', 80],
    ['numStreetsInList', 2, Number],
    ['listOfStreetCodes', 80, split(8)],
    ['listOfStreetNames', 320, split(32)],
  ],

  WA2_1: [ // pg 584
    ['_filler', 21],
    ['duplicateAddressIndicator', 1],
    ['lowHouseNumber', 11],
    ['highHouseNumber', 11],
    ['preferredLGC', 3],
    ['numCrossStreetsLow', 1],
    ['crossStreetsLow', 30, split(6)],
    ['numCrossStreetsHigh', 1],
    ['crossStreetsHigh', 30, split(6)],
    ['lionKey', 10],
    ['specialAddressGeneratedRecord', 1],
    ['sideOfStreet', 1],
    ['segmentLength', 5],
    ['xCoordinate', 7],
    ['yCoordinate', 7],
    ['_zCoordinate', 7],
    ['communityDevelopmentEligible', 1],
    ['alternativeBoroughFlag', 1],
    ['streetLightContractorArea', 1],
    ['communityDistrict', 3],
    ['zipCode', 5],
    ['electionDistrict', 3],
    ['assemblyDistrict', 2],
    ['splitElectionDistrict', 1],
    ['congressionalDistrict', 2],
    ['stateSenatorialDistrict', 2],
    ['civilCourtDistrict', 2],
    ['cityCouncilDistrict', 2],
    ['healthCenterDistrict', 2],
    ['healthArea', 4],
    ['sanitationDistrict', 3],
    ['sanitationCollectionSection', 2],
    ['sanitationRegularCollectionSchedule', 5],
    ['sanitationRecyclingCollectionSchedule', 3],
    ['policePatrolBoroughCommand', 1],
    ['policePrecinct', 3],
    ['fireDivision', 2],
    ['fireBatallion', 2],
    ['fireCompanyType', 1],
    ['fireCompanyNumber', 3],
    ['_filler', 1],
    ['communitySchoolDistrict', 2],
    ['atomicPolygon', 3],
    ['policePatrolBorough', 2],
    ['featureTypeCode', 1],
    ['segmentTypeCode', 1],
    ['alleyOrCrossStreetListFlag', 1],
    ['coincidenceSegmentCount', 1],
    ['_filler', 2],
    ['censusTractBorough', 1],
    ['censusTract1990', 6],
    ['censusTract2010', 6],
    ['censusBlock2010', 4],
    ['censusBlockSuffix2010', 1],
    ['censusTract2000', 6],
    ['censusBlock2000', 4],
    ['censusBlockSuffix2000', 1],
    ['neighborhoodTabulationArea', 4],
    ['snowPriorityCode', 1],
    ['organicRecyclingSchedule', 5],
    ['bulkPickupSchedule', 5],
    ['hurricaneEvacuationZone', 2],
    ['_filler', 11],
    ['underlyingAddressNumber', 11],
    ['underlyingB7SC', 8],
    ['segmentIdentifier', 7],
    ['curveFlag', 1]
  ],

  WA2_1X: [ // pg 587
    ['listOfLGC', 8],
    ['lgcPointer', 1],
    ['segmentAzimuth', 3],
    ['segmentOrientation', 1],
    ['xCoordinateSegmentLow', 7],
    ['yCoordinateSegmentLow', 7],
    ['zCoordinateSegmentLow', 7],
    ['xCoordinateSegmentHigh', 7],
    ['yCoordinateSegmentHigh', 7],
    ['zCoordinateSegmentHigh', 7],
    ['xCoordinate', 7],
    ['yCoordinate', 7],
    ['zCoordinate', 7],
    ['radius', 7],
    ['secantLocation', 1],
    ['angleFromNodeBeta', 5],
    ['angleToNodeAlpha', 5],
    ['fromLionNode', 7],
    ['toLionNode', 7],
    ['vanityLionKey', 10],
    ['vanitySideOfStreet', 1],
    ['splitLowHouseNumber', 11],
    ['trafficDirection', 1],
    ['turnRestrictions', 10],
    ['fractionForCurve', 3],
    ['roadwayType', 2],
    ['physicalId', 7],
    ['genericId', 7],
    ['nypdId', 7],
    ['fdnyId', 7],
    ['bikeLane2', 2],
    ['bikeTrafficDirection', 2],
    ['_filler', 3],
    ['streetStatus', 1],
    ['streetWidth', 3],
    ['streetWidthIrregular', 1],
    ['bikeLane', 1],
    ['federalClassificationCode', 2],
    ['rightOfWayType', 1],
    ['lisetOfSecond5LGC', 10, split(2)],
    ['legacySegmentId', 7],
    ['fromPreferredLGCFirst5', 10, split(2)],
    ['toPreferredLGCFirst5', 10, split(2)],
    ['fromPreferredLGCSecond5', 10, split(2)],
    ['toPreferredLGCSecond5', 10, split(2)],
    ['noCrossStreetCalculation', 1],
    ['individualSegmentLength', 5],
    ['ntaName', 75],
    ['uspsPreferredCityName', 25],
    ['latitude', 9, Number],
    ['longitude', 11, Number],
    ['fromActualSegmentNodeId', 7],
    ['toActualSegmentNodeId', 7],
    ['xCoordinateActualSegmentLow', 7],
    ['yCoordinateActualSegmentLow', 7],
    ['zCoordinateActualSegmentLow', 7],
    ['xCoordinateActualSegmentHigh', 7],
    ['yCoordinateActualSegmentHigh', 7],
    ['zCoordinateActualSegmentHigh', 7],
    ['blockfaceId', 10],
    ['numberOfTravelLanes', 2],
    ['numberOfParkingLanes', 2],
    ['numberOfTotalLanes', 2],
    ['streetWidthMaximum', 3],
    ['_filler', 252],
    ['reasonCode', 1],
    ['reasonCodeQualifier', 1],
    ['warningCodeFiller', 2],
    ['returnCode', 2],
    ['numberOfCrossStreetsLow', 1],
    ['listOfCrossStreetsLow', 40, split(8)],
    ['numberOfCrossStreetsHigh', 1],
    ['listOfCrossStreetsHigh', 40, split(8)],
    ['listOfCrossStreetNamesLow', 160, split(32)],
    ['listOfCrossStreetNamesHigh', 160, split(32)],
    ['preferredB7SC', 8],
    ['preferredStreetName', 32],
    ['_filler', 52],
  ],

  WA2_1A: [ // pg 590
    ['_filler', 21],
    ['duplicateAddressIndicator', 1, flag],
    ['lowHouseNumber', 11],
    ['bbl', 10],
    ['_filler', 1],
    ['bblSelfCheckCode', 1],
    ['_filler', 1],
    ['buildingClassificationCode', 2],
    ['cornerCode', 2],
    ['numberOfStructures', 4],
    ['numberOfStreetFrontages', 2],
    ['interiorLot', 1, flag],
    ['vacantLot', 1, flag],
    ['irregularlyShapedLot', 1, flag],
    ['alternateBorough', 1, flag],
    ['lgiOverflow', 1, flag],
    ['_filler', 19], // STROLLING KEY, Not Implemented
    ['_filler', 1],
    ['bin', 7],
    ['condo', 1, flag],
    ['_filler', 1],
    ['condoIdentificationNumber', 4],
    ['condoUnitIdNumber', 7],
    ['condoBillingBBL', 10],
    ['_filler', 1],
    ['condoBillingBBLSCC', 1],
    ['condoLowBBL', 10],
    ['_filler', 1],
    ['condoHighBBL', 10],
    ['_filler', 1],
    ['_filler', 15],
    ['coopIdNumber', 4],
    ['sbvp', 8],
    ['commercialStudyArea', 5],
    ['taxMapNumberSectionAndVolume', 5],
    ['_filler', 4],
    ['_filler', 3],
    ['latitude', 9, Number],
    ['longitude', 11, Number],
    ['xyCoordinates', 14],
    ['businessImprovementDistrict', 6],
    ['tpadBINStatus', 1],
    ['tpadNewBIN', 7],
    ['tpadNewBINStatus', 1],
    ['tpadConflict', 1, flag],
    ['_filler', 9],
    ['listOfLGC', 8, split(2)],
    ['numberOfGeoIdentifiers', 4],
    ['geoIdentifiers', 1113, subFormats.GEO_IDENTIFIER_53]
  ],

  WA2_1B: [ // pg 597
    // WA2-1
    ['_filler', 21],
    ['duplicateAddressIndicator', 1, flag],
    ['lowHouseNumber', 11],
    ['highHouseNumber', 11],
    ['lgc', 2],
    ['numberOfCrossStreetsLow', 1],
    ['crossStreetsLow', 30, split(6)],
    ['numberOfCrossStreetsHigh', 1],
    ['crossStreetsHigh', 30, split(6)],
    ['lionKey', 10],
    ['specialAddressGeneratedRecord', 1, flag],
    ['sideOfStreet', 1],
    ['segmentLength', 5],
    ['xyCoordinates', 14],
    ['_zCoordinate', 7],
    ['communityDevelopmentEligibility', 1, flag],
    ['alternativeBorough', 1, flag],
    ['streetLightContractorArea', 1, flag],
    ['communityDistrict', 3],
    ['zipCode', 5],
    ['electionDistrict', 3],
    ['assemblyDistrict', 2],
    ['splitElectionDistrict', 1, flag],
    ['congressionalDistrict', 2],
    ['stateSenatorialDistrict', 2],
    ['civilCourtDistrict', 2],
    ['cityCouncilDistrict', 2],
    ['healthCenterDistrict', 2],
    ['healthArea', 4],
    ['sanitationDistrict', 3],
    ['sanitationCollectionSection', 2],
    ['sanitationRegularCollectionSchedule', 5],
    ['sanitationRecyclingCollectionSchedule', 3],
    ['policePatrolBoroughCommand', 1],
    ['policePrecinct', 3],
    ['fireDivision', 2],
    ['fireBatallion', 2],
    ['fireCompanyType', 1],
    ['fireCompanyNumber', 3],
    ['_filler', 1],
    ['communitySchoolDistrict', 2],
    ['atomicPolygon', 3],
    ['policePatrolBorough', 2],
    ['featureTypeCode', 1],
    ['segmentTypeCode', 1],
    ['alleyOrCrossStreetListFlag', 1],
    ['coincidenceSegmentCount', 1],
    ['_filler', 3],
    ['censusTract1990', 6],
    ['censusTract2010', 6],
    ['censusBlock2010', 4],
    ['censusBlockSuffix2010', 1],
    ['censusTract2000', 6],
    ['censusBlock2000', 4],
    ['censusBlockSuffix2000', 1],
    ['neighborhoodTabulationArea', 4],
    ['snowPriorityCode', 1],
    ['organicRecyclingSchedule', 5],
    ['bulkPickupSchedule', 5],
    ['hurricaneEvacuationZone', 2],
    ['_filler', 11],
    ['underlyingAddressNumber', 11],
    ['underlyingB7SC', 8],
    ['segmentIdentifier', 7],
    ['curveFlag', 1],
    // WA2-1X
    ['listOfLGC', 8],
    ['lgcPointer', 1],
    ['segmentAzimuth', 3],
    ['segmentOrientation', 1],

    ['xCoordinateSegmentLow', 7],
    ['yCoordinateSegmentLow', 7],
    ['zCoordinateSegmentLow', 7],
    ['xCoordinateSegmentHigh', 7],
    ['yCoordinateSegmentHigh', 7],
    ['zCoordinateSegmentHigh', 7],
    ['xCoordinate', 7],
    ['yCoordinate', 7],
    ['zCoordinate', 7],
    ['radius', 7],
    ['secantLocation', 1],
    ['angleFromNodeBeta', 5],
    ['angleToNodeAlpha', 5],
    ['fromLionNode', 7],
    ['toLionNode', 7],
    ['vanityLionKey', 10],
    ['vanitySideOfStreet', 1],
    ['splitLowHouseNumber', 11],
    ['trafficDirection', 1],
    ['turnRestrictions', 10],
    ['fractionForCurve', 3],
    ['roadwayType', 2],
    ['physicalId', 7],
    ['genericId', 7],
    ['nypdId', 7],
    ['fdnyId', 7],
    ['bikeLane2', 2],
    ['bikeTrafficDirection', 2],
    ['_filler', 3],
    ['streetStatus', 1],
    ['streetWidth', 3],
    ['streetWidthIrregular', 1],
    ['bikeLane', 1],
    ['federalClassificationCode', 2],
    ['rightOfWayType', 1],
    ['lisetOfSecond5LGC', 10, split(2)],
    ['legacySegmentId', 7],
    ['fromPreferredLGCFirst5', 10, split(2)],
    ['toPreferredLGCFirst5', 10, split(2)],
    ['fromPreferredLGCSecond5', 10, split(2)],
    ['toPreferredLGCSecond5', 10, split(2)],
    ['noCrossStreetCalculation', 1],
    ['individualSegmentLength', 5],
    ['ntaName', 75],
    ['uspsPreferredCityName', 25],
    ['latitude', 9, Number],
    ['longitude', 11, Number],
    ['fromActualSegmentNodeId', 7],
    ['toActualSegmentNodeId', 7],
    ['xCoordinateActualSegmentLow', 7],
    ['yCoordinateActualSegmentLow', 7],
    ['zCoordinateActualSegmentLow', 7],
    ['xCoordinateActualSegmentHigh', 7],
    ['yCoordinateActualSegmentHigh', 7],
    ['zCoordinateActualSegmentHigh', 7],
    ['blockfaceId', 10],
    ['numberOfTravelLanes', 2],
    ['numberOfParkingLanes', 2],
    ['numberOfTotalLanes', 2],
    ['streetWidthMaximum', 3],
    ['_filler', 252],
    ['reasonCode', 1],
    ['reasonCodeQualifier', 1],
    ['warningCodeFiller', 2],
    ['returnCode', 2],
    ['numberOfCrossStreetsLow', 1],
    ['listOfCrossStreetsLow', 40, split(8)],
    ['numberOfCrossStreetsHigh', 1],
    ['listOfCrossStreetsHigh', 40, split(8)],
    ['listOfCrossStreetNamesLow', 160, split(32)],
    ['listOfCrossStreetNamesHigh', 160, split(32)],
    ['preferredB7SC', 8],
    ['preferredStreetName', 32],
    ['_filler', 52],

    // WA2-1A
    ['_filler', 21],
    ['duplicateAddressIndicator', 1, flag],
    ['lowHouseNumber', 11],
    ['bbl', 10],
    ['_filler', 1],
    ['bblSelfCheckCode', 1],
    ['_filler', 1],
    ['buildingClassificationCode', 2],
    ['cornerCode', 2],
    ['numberOfStructures', 4],
    ['numberOfStreetFrontages', 2],
    ['interiorLot', 1, flag],
    ['vacantLot', 1, flag],
    ['irregularlyShapedLot', 1, flag],
    ['alternateBorough', 1, flag],
    ['lgiOverflow', 1, flag],
    ['_filler', 19], // STROLLING KEY, Not Implemented
    ['_filler', 1],
    ['bin', 7],
    ['condo', 1, flag],
    ['_filler', 1],
    ['condoIdentificationNumber', 4],
    ['condoUnitIdNumber', 7],
    ['condoBillingBBL', 10],
    ['_filler', 1],
    ['condoBillingBBLSCC', 1],
    ['condoLowBBL', 10],
    ['_filler', 1],
    ['condoHighBBL', 10],
    ['_filler', 1],
    ['_filler', 15],
    ['coopIdNumber', 4],
    ['sbvp', 8],
    ['commercialStudyArea', 5],
    ['taxMapNumberSectionAndVolume', 5],
    ['_filler', 4],
    ['_filler', 3],
    ['latitude', 9, Number],
    ['longitude', 11, Number],
    ['xyCoordinates', 14],
    ['businessImprovementDistrict', 6],
    ['tpadBINStatus', 1],
    ['tpadNewBIN', 7],
    ['tpadNewBINStatus', 1],
    ['tpadConflict', 1, flag],
    ['_filler', 9],
    ['listOfLGC', 8, split(2)],
    ['numberOfGeoIdentifiers', 4],
    ['geoIdentifiers', 2436, subFormats.GEO_IDENTIFIER_116]
  ],

  WA2_AP: [ // pg 605
    ['_filler', 21],
    ['duplicateAddressIndicator', 1, flag],
    ['lowHouseNumber', 11],
    ['bbl', 10],
    ['_filler', 7],
    ['numberOfStructures', 4],
    ['_filler', 26],
    ['_filler', 1],
    ['bin', 7],
    ['condo', 1, flag],
    ['_filler', 1],
    ['condoIdNumber', 4],
    ['_filler', 7],
    ['condoBillingBBL', 10],
    ['_filler', 1],
    ['_filler', 1],
    ['condoLowBBL', 10],
    ['_filler', 1],
    ['condoHighBBL', 10],
    ['_filler', 1],
    ['_filler', 15],
    ['coopIdNumber', 4],
    ['_filler', 22],
    ['_filler', 3],
    ['latitude', 9, Number],
    ['longitude', 11, Number],
    ['xyCoordinates', 14],
    ['_filler', 16],
    ['addressPointId', 9],
    ['listOfLGC', 8, split(2)],
    ['numberOfGeoIdentifiers', 4],
    ['geoIdentifiers', 1113, subFormats.GEO_IDENTIFIER_53]
  ],

  WA2_2: [ // pg 608
    ['_filler', 21],
    ['intersectionReplicationCounter', 1],
    ['street1LGC', 2],
    ['street2LGC', 2],
    ['numIntersectingStreets', 1],
    ['listOfIntersectingStreets', 30, split(6)],
    ['compassDirectionOrCounter', 1],
    ['atomicPolygon', 3],
    ['_filler', 2],
    ['lionNodeNumber', 7],
    ['xCoordinate', 7],
    ['yCoordinate', 7],
    ['_zCoordinate', 7],
    ['sbvp1', 8],
    ['sbvp2', 8],
    ['alternativeBoroughFlag', 1],
    ['streetLightContractorArea', 1],
    ['communityDistrict', 3],
    ['zipCode', 5],
    ['healthArea', 4],
    ['policePatrolBoroughCommand', 1],
    ['policePrecinct', 3],
    ['fireDivision', 2],
    ['fireBattalion', 2],
    ['fireCompanyType', 1],
    ['fireCompanyNumber', 3],
    ['communitySchoolDistrict', 2],
    ['censusTract2010', 6],
    ['censusTract1990', 6],
    ['_pairsOfLevelCodes', 10],
    ['policePatrolBorough', 2],
    ['assemblyDistrict', 2],
    ['congressionalDistrict', 2],
    ['stateSenatorialDistrict', 2],
    ['civilCourtDistrict', 2],
    ['cityCouncilDistrict', 2],
    ['cdEligibility', 1],
    ['distanceBetweenDuplicateIntersections', 5],
    ['censusTract2000', 6],
    ['healthCenterDistrict', 2],
    ['sanitationDistrict', 3],
    ['sanitationSection', 2],
    ['_filler', 12],
  ],

  WA2_2W: [ // pg 610
    ['_filler', 22],
    ['street1LGC', 8],
    ['street2LGC', 8],
    ['turnRestrictions', 10],
    ['preferredLGC', 10],
    ['trueReplicationCounter', 2],
    ['listOfNodes', 140],
    ['nodeB7SC', 3200],
    ['reasonCode', 1],
    ['reasonCodeQualifier', 1],
    ['warningCode', 2],
    ['returnCode', 2],
    ['latitude', 9, Number],
    ['longitude', 11, Number],
    ['_filler', 374]
  ],
};

formats.WA2_1E = formats.WA2_1;
formats.WA2_1EX = formats.WA2_1X;
formats.WA2_BL = formats.WA2_1A;
formats.WA2_BN = formats.WA2_1A;

module.exports = formats;
