const f = require('../formatters');

module.exports = [ // pg 580
  ['firstBoroughName', 9],
  ['houseNumberDisplayFormat', 16],
  ['houseNumberSortFormat', 11],
  ['b10scFirstBorough', 11],
  ['firstStreetNameNormalized', 32],
  ['b10scSecondBorough', 11, f.removeIfEmpty],
  ['secondStreetNameNormalized', 32, f.removeIfEmpty],
  ['b10scThirdBorough', 11, f.removeIfEmpty],
  ['thirdStreetNameNormalized', 32, f.removeIfEmpty],
  ['bbl', 10, f.removeIfEmpty],
  ['_fillerTaxLotVersionNumber', 1],
  ['lowHouseNumberDisplayFormat', 16, f.removeIfEmpty],
  ['lowHouseNumberSortFormat', 11, f.removeIfEmpty],
  ['bin', 7, f.removeIfEmpty],
  ['streetAttributeIndicators', 3],
  ['reasonCode2', 1, f.removeIfEmpty],
  ['reasonCodeQualifier2', 1, f.removeIfEmpty],
  ['warningCode2', 2, f.removeIfEmpty],
  ['geosupportReturnCode2', 2, f.removeIfEmpty],
  ['message2', 80, f.removeIfEmpty],
  ['nodeNumber', 7],
  ['unitSortFormat', 14],
  ['unitDisplayFormat', 14],
  ['_filler', 11],
  ['napIdentificationNumber', 6],
  ['streetAttributeIndicator', 1],
  ['reasonCode', 1],
  ['reasonCodeQualifier', 1],
  ['warningCode', 2],
  ['geosupportReturnCode', 2],
  ['message', 80],
  ['numStreetsInList', 2, Number],
  ['listOfStreetCodes', 80, f.split(8)],
  ['listOfStreetNames', 320, f.split(32)],
];
