const f = require('../formatters');

module.exports = [ // pg 605
  ['_filler', 21],
  ['duplicateAddressIndicator', 1, f.flag],
  ['lowHouseNumber', 11],
  ['bbl', 10],
  ['_filler', 7],
  ['numberOfStructures', 4],
  ['_filler', 26],
  ['_filler', 1],
  ['bin', 7],
  ['condo', 1, f.flag],
  ['_filler', 1],
  ['condoIdNumber', 4],
  ['_filler', 7],
  ['condoBillingBBL', 10],
  ['_filler', 1],
  ['_filler', 1],
  ['condoLowBBL', 10],
  ['_filler', 1],
  ['condoHighBBL', 10],
  ['_filler', 1],
  ['_filler', 15],
  ['coopIdNumber', 4],
  ['_filler', 22],
  ['_filler', 3],
  ['latitude', 9, Number],
  ['longitude', 11, Number],
  ['xyCoordinates', 14],
  ['_filler', 16],
  ['addressPointId', 9],
  ['listOfLGC', 8, f.split(2)],
  ['numberOfGeoIdentifiers', 4],
  ['geoIdentifiers', 1113, require('./geo-identifier-53b')]
];
