const f = require('../formatters');

module.exports = [ // pg 608
  ['_filler', 21],
  ['intersectionReplicationCounter', 1],
  ['street1LGC', 2],
  ['street2LGC', 2],
  ['numIntersectingStreets', 1],
  ['listOfIntersectingStreets', 30, f.split(6)],
  ['compassDirectionOrCounter', 1],
  ['atomicPolygon', 3],
  ['_filler', 2],
  ['lionNodeNumber', 7],
  ['xCoordinate', 7],
  ['yCoordinate', 7],
  ['_zCoordinate', 7],
  ['sbvp1', 8],
  ['sbvp2', 8],
  ['alternativeBoroughFlag', 1],
  ['streetLightContractorArea', 1],
  ['communityDistrict', 3],
  ['zipCode', 5],
  ['healthArea', 4],
  ['policePatrolBoroughCommand', 1],
  ['policePrecinct', 3],
  ['fireDivision', 2],
  ['fireBattalion', 2],
  ['fireCompanyType', 1],
  ['fireCompanyNumber', 3],
  ['communitySchoolDistrict', 2],
  ['censusTract2010', 6],
  ['censusTract1990', 6],
  ['_pairsOfLevelCodes', 10],
  ['policePatrolBorough', 2],
  ['assemblyDistrict', 2],
  ['congressionalDistrict', 2],
  ['stateSenatorialDistrict', 2],
  ['civilCourtDistrict', 2],
  ['cityCouncilDistrict', 2],
  ['cdEligibility', 1],
  ['distanceBetweenDuplicateIntersections', 5],
  ['censusTract2000', 6],
  ['healthCenterDistrict', 2],
  ['sanitationDistrict', 3],
  ['sanitationSection', 2],
  ['_filler', 12],
];
