const f = require('../formatters');

module.exports = [ // pg 590
  ['_filler', 21],
  ['duplicateAddressIndicator', 1, f.flag],
  ['lowHouseNumber', 11],
  ['bbl', 10],
  ['_filler', 1],
  ['bblSelfCheckCode', 1],
  ['_filler', 1],
  ['buildingClassificationCode', 2],
  ['cornerCode', 2],
  ['numberOfStructures', 4],
  ['numberOfStreetFrontages', 2],
  ['interiorLot', 1, f.flag],
  ['vacantLot', 1, f.flag],
  ['irregularlyShapedLot', 1, f.flag],
  ['alternateBorough', 1, f.flag],
  ['lgiOverflow', 1, f.flag],
  ['_filler', 19], // STROLLING KEY, Not Implemented
  ['_filler', 1],
  ['bin', 7],
  ['condo', 1, f.flag],
  ['_filler', 1],
  ['condoIdentificationNumber', 4],
  ['condoUnitIdNumber', 7],
  ['condoBillingBBL', 10],
  ['_filler', 1],
  ['condoBillingBBLSCC', 1],
  ['condoLowBBL', 10],
  ['_filler', 1],
  ['condoHighBBL', 10],
  ['_filler', 1],
  ['_filler', 15],
  ['coopIdNumber', 4],
  ['sbvp', 8],
  ['commercialStudyArea', 5],
  ['taxMapNumberSectionAndVolume', 5],
  ['_filler', 4],
  ['_filler', 3],
  ['latitude', 9, Number],
  ['longitude', 11, Number],
  ['xyCoordinates', 14],
  ['businessImprovementDistrict', 6],
  ['tpadBINStatus', 1],
  ['tpadNewBIN', 7],
  ['tpadNewBINStatus', 1],
  ['tpadConflict', 1, f.flag],
  ['_filler', 9],
  ['listOfLGC', 8, f.split(2)],
  ['numberOfGeoIdentifiers', 4],
  ['geoIdentifiers', 1113, require('./geo-identifier-53b')]
];
