const f = require('../formatters');

module.exports = [ // pg 587
  ['listOfLGC', 8],
  ['lgcPointer', 1],
  ['segmentAzimuth', 3],
  ['segmentOrientation', 1],
  ['xCoordinateSegmentLow', 7],
  ['yCoordinateSegmentLow', 7],
  ['zCoordinateSegmentLow', 7],
  ['xCoordinateSegmentHigh', 7],
  ['yCoordinateSegmentHigh', 7],
  ['zCoordinateSegmentHigh', 7],
  ['xCoordinate', 7],
  ['yCoordinate', 7],
  ['zCoordinate', 7],
  ['radius', 7],
  ['secantLocation', 1],
  ['angleFromNodeBeta', 5],
  ['angleToNodeAlpha', 5],
  ['fromLionNode', 7],
  ['toLionNode', 7],
  ['vanityLionKey', 10],
  ['vanitySideOfStreet', 1],
  ['splitLowHouseNumber', 11],
  ['trafficDirection', 1],
  ['turnRestrictions', 10],
  ['fractionForCurve', 3],
  ['roadwayType', 2],
  ['physicalId', 7],
  ['genericId', 7],
  ['nypdId', 7],
  ['fdnyId', 7],
  ['bikeLane2', 2],
  ['bikeTrafficDirection', 2],
  ['_filler', 3],
  ['streetStatus', 1],
  ['streetWidth', 3],
  ['streetWidthIrregular', 1],
  ['bikeLane', 1],
  ['federalClassificationCode', 2],
  ['rightOfWayType', 1],
  ['lisetOfSecond5LGC', 10, f.split(2)],
  ['legacySegmentId', 7],
  ['fromPreferredLGCFirst5', 10, f.split(2)],
  ['toPreferredLGCFirst5', 10, f.split(2)],
  ['fromPreferredLGCSecond5', 10, f.split(2)],
  ['toPreferredLGCSecond5', 10, f.split(2)],
  ['noCrossStreetCalculation', 1],
  ['individualSegmentLength', 5],
  ['ntaName', 75],
  ['uspsPreferredCityName', 25],
  ['latitude', 9, Number],
  ['longitude', 11, Number],
  ['fromActualSegmentNodeId', 7],
  ['toActualSegmentNodeId', 7],
  ['xCoordinateActualSegmentLow', 7],
  ['yCoordinateActualSegmentLow', 7],
  ['zCoordinateActualSegmentLow', 7],
  ['xCoordinateActualSegmentHigh', 7],
  ['yCoordinateActualSegmentHigh', 7],
  ['zCoordinateActualSegmentHigh', 7],
  ['blockfaceId', 10],
  ['numberOfTravelLanes', 2],
  ['numberOfParkingLanes', 2],
  ['numberOfTotalLanes', 2],
  ['streetWidthMaximum', 3],
  ['_filler', 252],
  ['reasonCode', 1],
  ['reasonCodeQualifier', 1],
  ['warningCodeFiller', 2],
  ['returnCode', 2],
  ['numberOfCrossStreetsLow', 1],
  ['listOfCrossStreetsLow', 40, f.split(8)],
  ['numberOfCrossStreetsHigh', 1],
  ['listOfCrossStreetsHigh', 40, f.split(8)],
  ['listOfCrossStreetNamesLow', 160, f.split(32)],
  ['listOfCrossStreetNamesHigh', 160, f.split(32)],
  ['preferredB7SC', 8],
  ['preferredStreetName', 32],
  ['_filler', 52],
];
