const f = require('../formatters');

module.exports = [ // pg 597
  // WA2-1
  ['_filler', 21],
  ['duplicateAddressIndicator', 1, f.flag],
  ['lowHouseNumber', 11],
  ['highHouseNumber', 11],
  ['lgc', 2],
  ['numberOfCrossStreetsLow', 1],
  ['crossStreetsLow', 30, f.split(6)],
  ['numberOfCrossStreetsHigh', 1],
  ['crossStreetsHigh', 30, f.split(6)],
  ['lionKey', 10],
  ['specialAddressGeneratedRecord', 1, f.flag],
  ['sideOfStreet', 1],
  ['segmentLength', 5],
  ['xyCoordinates', 14],
  ['_zCoordinate', 7],
  ['communityDevelopmentEligibility', 1, f.flag],
  ['alternativeBorough', 1, f.flag],
  ['streetLightContractorArea', 1, f.flag],
  ['communityDistrict', 3],
  ['zipCode', 5],
  ['electionDistrict', 3],
  ['assemblyDistrict', 2],
  ['splitElectionDistrict', 1, f.flag],
  ['congressionalDistrict', 2],
  ['stateSenatorialDistrict', 2],
  ['civilCourtDistrict', 2],
  ['cityCouncilDistrict', 2],
  ['healthCenterDistrict', 2],
  ['healthArea', 4],
  ['sanitationDistrict', 3],
  ['sanitationCollectionSection', 2],
  ['sanitationRegularCollectionSchedule', 5],
  ['sanitationRecyclingCollectionSchedule', 3],
  ['policePatrolBoroughCommand', 1],
  ['policePrecinct', 3],
  ['fireDivision', 2],
  ['fireBatallion', 2],
  ['fireCompanyType', 1],
  ['fireCompanyNumber', 3],
  ['_filler', 1],
  ['communitySchoolDistrict', 2],
  ['atomicPolygon', 3],
  ['policePatrolBorough', 2],
  ['featureTypeCode', 1],
  ['segmentTypeCode', 1],
  ['alleyOrCrossStreetListFlag', 1],
  ['coincidenceSegmentCount', 1],
  ['_filler', 3],
  ['censusTract1990', 6],
  ['censusTract2010', 6],
  ['censusBlock2010', 4],
  ['censusBlockSuffix2010', 1],
  ['censusTract2000', 6],
  ['censusBlock2000', 4],
  ['censusBlockSuffix2000', 1],
  ['neighborhoodTabulationArea', 4],
  ['snowPriorityCode', 1],
  ['organicRecyclingSchedule', 5],
  ['bulkPickupSchedule', 5],
  ['hurricaneEvacuationZone', 2],
  ['_filler', 11],
  ['underlyingAddressNumber', 11],
  ['underlyingB7SC', 8],
  ['segmentIdentifier', 7],
  ['curveFlag', 1],
  // WA2-1X
  ['listOfLGC', 8],
  ['lgcPointer', 1],
  ['segmentAzimuth', 3],
  ['segmentOrientation', 1],

  ['xCoordinateSegmentLow', 7],
  ['yCoordinateSegmentLow', 7],
  ['zCoordinateSegmentLow', 7],
  ['xCoordinateSegmentHigh', 7],
  ['yCoordinateSegmentHigh', 7],
  ['zCoordinateSegmentHigh', 7],
  ['xCoordinate', 7],
  ['yCoordinate', 7],
  ['zCoordinate', 7],
  ['radius', 7],
  ['secantLocation', 1],
  ['angleFromNodeBeta', 5],
  ['angleToNodeAlpha', 5],
  ['fromLionNode', 7],
  ['toLionNode', 7],
  ['vanityLionKey', 10],
  ['vanitySideOfStreet', 1],
  ['splitLowHouseNumber', 11],
  ['trafficDirection', 1],
  ['turnRestrictions', 10],
  ['fractionForCurve', 3],
  ['roadwayType', 2],
  ['physicalId', 7],
  ['genericId', 7],
  ['nypdId', 7],
  ['fdnyId', 7],
  ['bikeLane2', 2],
  ['bikeTrafficDirection', 2],
  ['_filler', 3],
  ['streetStatus', 1],
  ['streetWidth', 3],
  ['streetWidthIrregular', 1],
  ['bikeLane', 1],
  ['federalClassificationCode', 2],
  ['rightOfWayType', 1],
  ['lisetOfSecond5LGC', 10, f.split(2)],
  ['legacySegmentId', 7],
  ['fromPreferredLGCFirst5', 10, f.split(2)],
  ['toPreferredLGCFirst5', 10, f.split(2)],
  ['fromPreferredLGCSecond5', 10, f.split(2)],
  ['toPreferredLGCSecond5', 10, f.split(2)],
  ['noCrossStreetCalculation', 1],
  ['individualSegmentLength', 5],
  ['ntaName', 75],
  ['uspsPreferredCityName', 25],
  ['latitude', 9, Number],
  ['longitude', 11, Number],
  ['fromActualSegmentNodeId', 7],
  ['toActualSegmentNodeId', 7],
  ['xCoordinateActualSegmentLow', 7],
  ['yCoordinateActualSegmentLow', 7],
  ['zCoordinateActualSegmentLow', 7],
  ['xCoordinateActualSegmentHigh', 7],
  ['yCoordinateActualSegmentHigh', 7],
  ['zCoordinateActualSegmentHigh', 7],
  ['blockfaceId', 10],
  ['numberOfTravelLanes', 2],
  ['numberOfParkingLanes', 2],
  ['numberOfTotalLanes', 2],
  ['streetWidthMaximum', 3],
  ['_filler', 252],
  ['reasonCode', 1],
  ['reasonCodeQualifier', 1],
  ['warningCodeFiller', 2],
  ['returnCode', 2],
  ['numberOfCrossStreetsLow', 1],
  ['listOfCrossStreetsLow', 40, f.split(8)],
  ['numberOfCrossStreetsHigh', 1],
  ['listOfCrossStreetsHigh', 40, f.split(8)],
  ['listOfCrossStreetNamesLow', 160, f.split(32)],
  ['listOfCrossStreetNamesHigh', 160, f.split(32)],
  ['preferredB7SC', 8],
  ['preferredStreetName', 32],
  ['_filler', 52],

  // WA2-1A
  ['_filler', 21],
  ['duplicateAddressIndicator', 1, f.flag],
  ['lowHouseNumber', 11],
  ['bbl', 10],
  ['_filler', 1],
  ['bblSelfCheckCode', 1],
  ['_filler', 1],
  ['buildingClassificationCode', 2],
  ['cornerCode', 2],
  ['numberOfStructures', 4],
  ['numberOfStreetFrontages', 2],
  ['interiorLot', 1, f.flag],
  ['vacantLot', 1, f.flag],
  ['irregularlyShapedLot', 1, f.flag],
  ['alternateBorough', 1, f.flag],
  ['lgiOverflow', 1, f.flag],
  ['_filler', 19], // STROLLING KEY, Not Implemented
  ['_filler', 1],
  ['bin', 7],
  ['condo', 1, f.flag],
  ['_filler', 1],
  ['condoIdentificationNumber', 4],
  ['condoUnitIdNumber', 7],
  ['condoBillingBBL', 10],
  ['_filler', 1],
  ['condoBillingBBLSCC', 1],
  ['condoLowBBL', 10],
  ['_filler', 1],
  ['condoHighBBL', 10],
  ['_filler', 1],
  ['_filler', 15],
  ['coopIdNumber', 4],
  ['sbvp', 8],
  ['commercialStudyArea', 5],
  ['taxMapNumberSectionAndVolume', 5],
  ['_filler', 4],
  ['_filler', 3],
  ['latitude', 9, Number],
  ['longitude', 11, Number],
  ['xyCoordinates', 14],
  ['businessImprovementDistrict', 6],
  ['tpadBINStatus', 1],
  ['tpadNewBIN', 7],
  ['tpadNewBINStatus', 1],
  ['tpadConflict', 1, f.flag],
  ['_filler', 9],
  ['_filler', 8],
  ['reasonCode', 1],
  ['reasonCodeQualifier', 1],
  ['warningCode', 2],
  ['returnCode', 2],
  ['filler', 108],
  ['numberOfGeoIdentifiers', 4],
  ['geoIdentifiers', 2436,  require('./geo-identifier-116b')]
];
